FROM oven/bun:latest

ARG PUBLIC_POCKETBASE_URL
ARG PUBLIC_APPLICATION_NAME
ARG PUBLIC_APPLICATION_URL
ARG ENCRYPTION
ARG POCKETBASE_ADMIN_EMAIL
ARG POCKETBASE_ADMIN_PASSWORD
ARG METADATA_SCRAPER_URL
ARG HASH_ALGORITHM
ARG HASH_KEY
ARG STRIPE_SECRET_KEY
ARG STRIPE_WEBHOOK_SECRET
ARG STRIPE_PRO_PRICE_ID
ARG STRIPE_ENTERPRISE_PRICE_ID
ARG PUBLIC_SITE_URL
ARG STRIPE_PRODUCT_ID
ARG ORIGIN

WORKDIR /app
COPY package.json package.json
RUN bun install

COPY . .
RUN bun run build

EXPOSE 3000
CMD ["bun", "--bun", "build/index.js"]
